### ISSUE TITLE
react-map-gl-amplify-change-map-language: Esri map not displaying full localization

### ISSUE THREAD

**Issue by NguyenDOanNhan** [aws-samples/amazon-location-samples#115] opened 2022-02-14 10:40 UTC
I tried changing it to Japanese, and trying to zoom in on places in Tokyo City, the English names are still displayed

![2022-02-14_17-35-50](https://user-images.githubusercontent.com/43739331/153848745-ecbee8bf-10f9-4030-a63c-f93ec297446f.png)

**Comment by dreamorosi** [comment] 2022-02-14 13:49
Just tried to reproduce this.

With HERE maps I don't see the same behaviour:
![](https://user-images.githubusercontent.com/7353869/153862756-03e4157c-f4ec-4331-9ed5-aff2701a805c.mp4)

While with Esri maps I am able to observe the same behaviour as your screenshot.

As mentioned in the README file I have lifted the implementation from these two examples:
[Amazon Location Maps -- Localization of Esri styles](https://observablehq.com/d/d33cd2634b2e2137)
[Amazon Location Maps -- Localization of HERE styles](https://observablehq.com/d/ae773856b183964e)

These were made by @mojodna, another maintainer of this repo.

I'm not sure on whether the differences we are seeing are due to the difference in data available / data quality from the two Amazon Location Service providers or if there's an error in the transformation of the style descriptor, I would like @mojodna to confirm since he might know more than me.

**Comment by NguyenDOanNhan** [comment] 2022-02-15 02:34
OKi, I have seen the code instructions in this article
See if it's useful to you!
https://dev.classmethod.jp/articles/tips-amazon-location-service-map-localization/

**Comment by dreamorosi** [comment] 2022-02-15 08:57
Thank you for sharing the link @NguyenDOanNhan, the implementation in the sample uses a [map function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) instead of a for loop but that should be equivalent in terms of end result.

See [L180](https://github.com/aws-samples/amazon-location-samples/blob/main/react-map-gl-amplify-change-map-language/src/hooks/useLocalizedStyleDescriptor.js#L180) (the map function on layers) that calls one of the two functions that apply the transformation (i.e. [this](https://github.com/aws-samples/amazon-location-samples/blob/main/react-map-gl-amplify-change-map-language/src/hooks/useLocalizedStyleDescriptor.js#L51)).

Aside from that, the interesting thing showed in your link is that they are using the `{_name_local}` string, which in our sample corresponds to the "Local" one:

![Screenshot 2022-02-15 at 09 31 33](https://user-images.githubusercontent.com/7353869/154023038-a8bff6aa-69b7-4de2-856a-a02d8d182e9e.png)

As you see from the screenshot above, at least when using the map _above_ Japan, the "Local" setting seems to perform better than the "Global" and "Japanese".

I have also have been asking internally and I've confirmed what the Amazon Location Service developer guide ([link](https://docs.aws.amazon.com/location/latest/developerguide/what-is-data-provider.html)) says:
> Each provider gathers and curates their data using different means. They may also have varying expertise in different regions of the world. This section provides details about our data providers. You may select any data provider based on your preference.

In practice I would recommend you, and other customers, to test & chose the map provider & language code that better suits your need and better performs in your use case.

Given that the purpose of this repo is to provide code samples I'll be closing this issue as solved given that the sample works despite different behaviours with each data provider & different language code combinations. Later today I'll also add an additional paragraph to the sample's README file to clarify this aspect.

If you find other issues with the code in the samples please feel free to open another issue.

Thank you again for taking the time to not only report but also take the time to look for resources on your side.

**Closed** 2022-02-15 09:11 UTC
Labels: question

**Comment by NguyenDOanNhan** [comment] 2022-02-15 09:13
Thank you very much, I understood the problem.
